// scripts/generate-fonts.js
//
// Run this with Node from your module folder:
//
//   cd C:\Users\Username\AppData\Local\FoundryVTT\Data\modules\dg-font-pack
//   node scripts\generate-fonts.js
//
// It will:
//   - read every font file in ./fonts
//   - generate styles/fonts.css with @font-face rules
//   - generate scripts/auto-font-defs.js to populate CONFIG.fontDefinitions
//

const fs = require("fs");
const path = require("path");

// ---- CHANGE THIS IF YOUR MODULE FOLDER NAME IS DIFFERENT ----
const moduleId = "dg-font-pack"; // matches Data/modules/dg-font-pack
// --------------------------------------------------------------

// Base dirs relative to this script
const rootDir = path.join(__dirname, "..");      // .../dg-font-pack
const fontsDir = path.join(rootDir, "fonts");    // .../dg-font-pack/fonts
const stylesDir = path.join(rootDir, "styles");  // .../dg-font-pack/styles
const scriptsDir = path.join(rootDir, "scripts");// .../dg-font-pack/scripts

const cssOut = path.join(stylesDir, "fonts.css");
const defsOut = path.join(scriptsDir, "auto-font-defs.js");

// Ensure dirs exist
fs.mkdirSync(fontsDir, { recursive: true });
fs.mkdirSync(stylesDir, { recursive: true });
fs.mkdirSync(scriptsDir, { recursive: true });

/**
 * Turn a filename into a font-family name:
 *   - strip extension
 *   - replace underscores / multiple spaces with a single space
 */
function makeFontFamilyName(filename) {
  const base = filename.replace(/\.[^.]+$/, "");
  return base
    .replace(/[_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Collect font files
const files = fs.readdirSync(fontsDir).filter((file) =>
  /\.(ttf|otf|woff|woff2|fon)$/i.test(file)
);

if (!files.length) {
  console.warn("⚠ No font files found in fonts/ – put them there and run again.");
}

// =======================
// 1) Generate fonts.css
// =======================
let css = `/* Auto-generated by scripts/generate-fonts.js
   Source folder: fonts/
   DO NOT EDIT BY HAND – rerun the generator instead.
*/

`;

for (const file of files) {
  const family = makeFontFamilyName(file);

  css += `@font-face {
  font-family: "${family}";
  src: url("../fonts/${file}");
  font-weight: normal;
  font-style: normal;
}

`;
}

fs.writeFileSync(cssOut, css, "utf8");
console.log(`✅ Wrote ${cssOut} with ${files.length} @font-face rules.`);

// ==============================
// 2) Generate auto-font-defs.js
// ==============================
let js = `// Auto-generated by scripts/generate-fonts.js
// This runs on Foundry init and registers all fonts found in fonts/.
// DO NOT EDIT BY HAND – rerun the generator instead.

Hooks.once("init", () => {
  CONFIG.fontDefinitions = CONFIG.fontDefinitions || {};
  const defs = CONFIG.fontDefinitions;
`;

// If there are duplicate "families" (same filename base), we just let the
// last one win. That's fine for your use case.
for (const file of files) {
  const family = makeFontFamilyName(file);
  const url = `modules/${moduleId}/fonts/${file}`.replace(/\\/g, "/");

  js += `
  defs["${family}"] = {
    editor: true,
    fonts: [
      {
        urls: ["${url}"],
        weight: "normal",
        style: "normal"
      }
    ]
  };`;
}

js += `
});
`;

fs.writeFileSync(defsOut, js, "utf8");
console.log(`✅ Wrote ${defsOut} with ${files.length} fontDefinitions.`);
console.log("Done. Enable the module in Foundry and your fonts should appear.");
